- hosts: opiesz
  become: true
  tasks:
    - name: Configure green LED activity
      shell: sed '$iecho mmc1> /sys/class/leds/orangepi\\:green\\:status/trigger' /etc/rc.local > temp && mv temp /etc/rc.local && chmod +x /etc/rc.local

    - name: Configure red LED activity
      shell: sed '$iecho mmc0> /sys/class/leds/orangepi\\:red\\:power/trigger' /etc/rc.local > temp && mv temp /etc/rc.local && chmod +x /etc/rc.local

    - name: Set hostname
      shell: hostnamectl set-hostname {{ hostname }}
      
    - name: Install Avahi
      shell: apt-get install avahi-daemon -y
