- hosts: "{{ lookup('env', 'TARGET_GROUP_NAME') | default('opies', true) }}"
  become: yes
  tasks:
    - name: Install K3s on the master node
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="--disable traefik \
                          --disable servicelb \
                          --disable cloud-controller \
                          --disable network-policy" \
        sh -s - server --cluster-init
      when: master | default(false)

    - name: Set master_ip fact
      set_fact:
        master_ip: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        cacheable: true
      run_once: true
      with_items: "{{ groups[lookup('env', 'TARGET_GROUP_NAME') | default('opies', true)] }}"
      when: hostvars[item]['master'] | default(false)

    - name: Get K3s token from master
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token_result
      delegate_to: "{{ item }}"
      run_once: true
      with_items: "{{ groups[lookup('env', 'TARGET_GROUP_NAME') | default('opies', true)] }}"
      when: hostvars[item]['master'] | default(false)

    - name: Set k3s_token fact
      set_fact:
        k3s_token: "{{ k3s_token_result.results[0].stdout }}"
        cacheable: true
      run_once: true

- hosts: "{{ lookup('env', 'TARGET_GROUP_NAME') | default('opies', true) }}"
  become: yes
  tasks:
    - name: Install K3s on worker nodes
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL=https://{{ master_ip }}:6443 \
        K3S_TOKEN={{ k3s_token }} sh -
      when: master is not defined or not master

- hosts: "{{ lookup('env', 'TARGET_GROUP_NAME') | default('opies', true) }}"
  become: yes
  tasks:
    - name: Wait for server to start
      shell: "sleep 10"
      when: master | default(false)

    - name: Verify K3s installation
      shell: KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl get nodes
      register: result
      ignore_errors: true
      when: master | default(false)

    - debug:
        var: result.stdout_lines
      when: master | default(false)
