---
- hosts: 192.168.1.161
  become: yes
  gather_facts: no
  tasks:
    - name: Install Helm using apt
      apt:
        name: helm
        state: present
        update_cache: yes

    - name: Add MariaDB Operator Helm repository
      shell: helm repo add mariadb-operator https://helm.mariadb.com/mariadb-operator
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Install MariaDB Operator CRDs
      shell: helm install mariadb-operator-crds mariadb-operator/mariadb-operator-crds
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Install MariaDB Operator
      shell: helm install mariadb-operator mariadb-operator/mariadb-operator
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
