- hosts: "{{ lookup('env', 'TARGET_GROUP_NAME') | default('opies', true) }}"_workers
  become: true
  tasks:
    - name: Leave swarm (workers)
      shell: docker swarm leave

- hosts: "{{ lookup('env', 'TARGET_GROUP_NAME') | default('opies', true) }}"_manager
  become: true
  tasks:
    - name: Leave swarm (manager)
      shell: docker swarm leave --force
