- hosts: "{{ lookup('env', 'TARGET_GROUP_NAME') | default('opies', true) }}"
  become: yes
  tasks:
    - name: Uninstall K3s
      shell: /usr/local/bin/k3s-uninstall.sh || true
      ignore_errors: yes

    - name: Unmount /var/lib/kubelet submounts
      shell: |
        mount | grep /var/lib/kubelet | awk '{print $3}' | sort -r | xargs -r umount
      ignore_errors: yes

    - name: Remove leftover directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher
        - /var/lib/rancher
        - /var/lib/kubelet
