- hosts: opies
  become: yes
  tasks:
    - name: Uninstall K3s
      shell: /usr/local/bin/k3s-uninstall.sh || true
      ignore_errors: yes

    - name: Remove leftover directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher
        - /var/lib/rancher
        - /var/lib/kubelet
