- name: Undeploy MariaDB stack
  hosts: opies_manager
  tasks:
    - name: Remove MariaDB stack
      shell: docker stack rm mariadb

- name: Delete files
  hosts: opies
  become: true
  tasks:
    - name: Delete data and files directories
      shell: rm -rf /home/orangepi/mariadb-1-data/ /home/orangepi/mariadb-2-data/ /home/orangepi/mariadb-3-data/ /home/orangepi/maxscale-data/ /home/orangepi/files/
