- name: Updates and upgrades the nodes
  hosts: "{{ lookup('env', 'TARGET_GROUP_NAME') | default('opies', true) }}"
  tasks:
    - name: Update package lists
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
