apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  replicas: 3
  replicasAllowEvenNumber: true
  rootPasswordSecretKeyRef:
    name: root-password
    key: password
    generate: false
  storage:
    size: 100Mi
    storageClassName: local-path
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1500m
  galera:
    enabled: true
    sst: mariabackup
    primary:
      podIndex: 0
  myCnf: |
    [mariadb]
    bind-address=0.0.0.0
    binlog_format=ROW
    innodb_buffer_pool_size=64M
    max_connections=12
    wsrep_sst_auth=root:demo123
    wsrep_provider_options=gcache.size=128M; gcache.page_size=128M
  startupProbe:
    failureThreshold: 40         # 40 * 15s = 10 minutes grace
    periodSeconds: 15            # check every 15 seconds
    timeoutSeconds: 10           # each check can take up to 10s
  livenessProbe:
    failureThreshold: 10         # 10 * 60s = 10 minutes of failing allowed
    periodSeconds: 60            # check every 60 seconds
    timeoutSeconds: 10           # each check can take 10s
  readinessProbe:
    failureThreshold: 10         # 10 * 30s = 5 minutes tolerance
    periodSeconds: 30            # check every 30 seconds
    timeoutSeconds: 5            # fast readiness check
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-external
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
