apiVersion: v1
kind: Secret
metadata:
  name: mariadb-galera-root-password
type: Opaque
stringData:
  password: demo123
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  replicas: 3
  rootPasswordSecretKeyRef:
    name: mariadb-galera-root-password
    key: password
  storage:
    size: 100Mi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 300m
  galera:
    enabled: true
    sst: mariabackup
    primary:
      podIndex: 0
  myCnf: |
    [mariadb]
    bind-address=0.0.0.0
    binlog_format=ROW
    innodb_buffer_pool_size=64M
    max_connections=20
    wsrep_on=ON
    wsrep_provider=/usr/lib/galera/libgalera_smm.so
    wsrep_cluster_address=gcomm://
    wsrep_cluster_name=galera_cluster
    wsrep_node_address=auto
    wsrep_node_name=auto
    wsrep_sst_method=mariabackup
    wsrep_sst_auth=root:demo123
    wsrep_provider_options=gcache.size=128M; gcache.page_size=128M
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-external
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
