# MariaDB instance
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-demo
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root-password
    key: password
  storage:
    size: 100Mi
    storageClassName: local-path
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 512Mi
  myCnf: |
    [mariadb]
    bind-address=0.0.0.0
    skip-log-bin
    innodb_buffer_pool_size=358M
    max_connections=20
  startupProbe:
    failureThreshold: 40         # 40 * 15s = 10 minutes grace
    periodSeconds: 15            # check every 15 seconds
    timeoutSeconds: 10           # each check can take up to 10s
  livenessProbe:
    failureThreshold: 10         # 10 * 60s = 10 minutes of failing allowed
    periodSeconds: 60            # check every 60 seconds
    timeoutSeconds: 10           # each check can take 10s
  readinessProbe:
    failureThreshold: 10         # 10 * 30s = 5 minutes tolerance
    periodSeconds: 30            # check every 30 seconds
    timeoutSeconds: 5            # fast readiness check
---
# NodePort service
apiVersion: v1
kind: Service
metadata:
  name: mariadb-demo-external
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
